import { useMemo, useState } from "react";
import {
  BarChart3, Check, CheckSquare, ChevronLeft, ChevronRight, Download, Edit3,
  Plus, Settings, Sparkles, Target, Trash2, WalletCards, X, TrendingUp, Trophy, Zap, Coins,
  TrendingDown, PiggyBank, CalendarDays, Bell, Moon, Sun, RotateCcw, type LucideIcon
} from "lucide-react";
import {
  addMonths, eachDayOfInterval, endOfMonth, format, isSameDay, isSameMonth,
  isToday, parseISO, startOfMonth, subMonths
} from "date-fns";
import { ru } from "date-fns/locale";
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from "recharts";
import { useStore } from "./store";
import type { Habit, Priority, RepeatRule, TransactionType } from "./types";
import { ACHIEVEMENTS, levelProgress } from "./gamification";

type Tab="habits"|"tasks"|"finance"|"analytics"|"profile";
const today=()=>format(new Date(),"yyyy-MM-dd");
const money=(n:number)=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(n);

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 p-3 sm:items-center">
    <div className="card max-h-[92vh] w-full max-w-xl overflow-y-auto p-5 shadow-2xl">
      <div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">{title}</h2><button onClick={onClose}><X/></button></div>{children}
    </div>
  </div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-3 block"><span className="muted text-sm">{label}</span>{children}</label>}
function Input(p:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className="mt-1 w-full rounded-xl border-0 p-3 outline-none" />}
function Select(p:React.SelectHTMLAttributes<HTMLSelectElement>){return <select {...p} className="mt-1 w-full rounded-xl border-0 p-3 outline-none"/>}
function Page({title,action,children}:{title:string;action?:React.ReactNode;children:React.ReactNode}){
  return <main className="safe-bottom mx-auto max-w-2xl px-4 pt-5"><header className="mb-5 flex items-center justify-between"><h1 className="text-2xl font-black">{title}</h1>{action}</header>{children}</main>
}
function Pill({children}:{children:React.ReactNode}){return <span className="rounded-full bg-black/5 px-2.5 py-1 text-xs dark:bg-white/10">{children}</span>}
function calcStreak(ds:string[]){const s=new Set(ds);let n=0,d=new Date();while(s.has(format(d,"yyyy-MM-dd"))){n++;d.setDate(d.getDate()-1)}return n}
function bestStreak(ds:string[]){if(!ds.length)return 0;const a=[...new Set(ds)].sort();let best=1,cur=1;for(let i=1;i<a.length;i++){const d1=new Date(a[i-1]+"T00:00:00"),d2=new Date(a[i]+"T00:00:00");if((d2.getTime()-d1.getTime())===86400000){cur++;best=Math.max(best,cur)}else cur=1}return best}

function GamificationCard(){
  const {gamification}=useStore();
  const p=levelProgress(gamification.xp);
  return <div className="card mb-4 overflow-hidden p-5">
    <div className="flex items-center gap-3">
      <div className="flex h-12 w-12 items-center justify-center rounded-2xl primary"><Trophy size={23}/></div>
      <div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><div><span className="muted text-sm">Твой уровень</span><div className="text-2xl font-black">Level {p.level}</div></div><div className="text-right"><div className="flex items-center justify-end gap-1 font-black"><Zap size={16}/> {gamification.xp} XP</div><div className="muted flex items-center justify-end gap-1 text-sm"><Coins size={14}/> {gamification.coins} монет</div></div></div></div>
    </div>
    <div className="mt-4 h-2 overflow-hidden rounded-full bg-black/10"><div className="primary h-full rounded-full transition-all" style={{width:`${p.pct}%`}}/></div>
    <div className="muted mt-2 flex justify-between text-xs"><span>{p.current} / {p.needed} XP до следующего уровня</span><span>{p.pct}%</span></div>
  </div>
}

function Habits(){
  const {habits,addHabit,updateHabit,toggleHabit,removeHabit}=useStore();
  const [open,setOpen]=useState(false),[edit,setEdit]=useState<Habit|null>(null),[month,setMonth]=useState(new Date());
  const [name,setName]=useState(""),[cat,setCat]=useState("Личное"),[color,setColor]=useState("#2481cc"),[reminder,setReminder]=useState("");
  const done=habits.filter(h=>h.completions.includes(today())).length, pct=habits.length?Math.round(done/habits.length*100):0;
  const days=eachDayOfInterval({start:startOfMonth(month),end:endOfMonth(month)});
  const openEdit=(h?:Habit)=>{if(h){setEdit(h);setName(h.name);setCat(h.category);setColor(h.color);setReminder(h.reminder??"")}else{setEdit(null);setName("");setCat("Личное");setColor("#2481cc");setReminder("")}setOpen(true)};
  const save=()=>{if(!name.trim())return;const v={name:name.trim(),category:cat.trim()||"Личное",color,reminder:reminder||undefined};edit?updateHabit(edit.id,v):addHabit(v);setOpen(false)};
  return <Page title="Привычки" action={<button className="primary rounded-full p-3" onClick={()=>openEdit()}><Plus/></button>}>
    <GamificationCard/>
    <div className="card mb-4 p-5"><div className="flex justify-between"><div><div className="muted">Сегодня</div><div className="text-3xl font-black">{done}/{habits.length}</div></div><div className="text-right"><div className="muted">Выполнение</div><div className="text-2xl font-black">{pct}%</div></div></div><div className="mt-4 h-2 rounded-full bg-black/10"><div className="primary h-2 rounded-full transition-all" style={{width:`${pct}%`}}/></div></div>
    <div className="mb-3 flex items-center justify-between"><button onClick={()=>setMonth(subMonths(month,1))}><ChevronLeft/></button><b>{format(month,"LLLL yyyy",{locale:ru})}</b><button onClick={()=>setMonth(addMonths(month,1))}><ChevronRight/></button></div>
    <div className="mb-4 grid grid-cols-7 gap-1 text-center text-xs">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x=><span className="muted" key={x}>{x}</span>)}{Array.from({length:(startOfMonth(month).getDay()+6)%7}).map((_,i)=><span key={"e"+i}/>)}{days.map(d=><span key={d.toISOString()} className={`rounded-lg p-1 ${isToday(d)?"primary font-bold":""}`}>{format(d,"d")}</span>)}</div>
    <div className="space-y-3">{habits.map(h=>{const d=h.completions.includes(today()),st=calcStreak(h.completions);return <div className="card p-4" key={h.id}><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl text-white" style={{background:h.color}}><Target size={21}/></div><div className="min-w-0 flex-1"><div className="truncate font-bold">{h.name}</div><div className="muted text-sm">{h.category} · 🔥 {st} · рекорд {bestStreak(h.completions)}</div></div><button onClick={()=>toggleHabit(h.id)} className={`rounded-xl px-3 py-2 font-bold ${d?"bg-green-500 text-white":"bg-black/5 dark:bg-white/10"}`}>{d?<Check/>:"Сегодня"}</button></div><div className="mt-3 flex gap-2"><button className="muted flex items-center gap-1 text-sm" onClick={()=>openEdit(h)}><Edit3 size={15}/> Изменить</button><button className="muted flex items-center gap-1 text-sm" onClick={()=>removeHabit(h.id)}><Trash2 size={15}/> Удалить</button>{h.reminder&&<Pill>⏰ {h.reminder}</Pill>}</div></div>})}</div>
    {open&&<Modal title={edit?"Изменить привычку":"Новая привычка"} onClose={()=>setOpen(false)}><Field label="Название"><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Например, читать 20 минут"/></Field><Field label="Категория"><Input value={cat} onChange={e=>setCat(e.target.value)}/></Field><Field label="Напоминание"><Input type="time" value={reminder} onChange={e=>setReminder(e.target.value)}/></Field><Field label="Цвет"><Input type="color" value={color} onChange={e=>setColor(e.target.value)} className="h-12"/></Field><button className="primary w-full rounded-xl p-3 font-bold" onClick={save}>{edit?"Сохранить":"Создать"}</button></Modal>}
  </Page>
}

function Tasks(){
  const {tasks,addTask,toggleTask,removeTask}=useStore();const [open,setOpen]=useState(false),[filter,setFilter]=useState("all"),[title,setTitle]=useState(""),[priority,setPriority]=useState<Priority>("medium"),[due,setDue]=useState(today()),[repeat,setRepeat]=useState<RepeatRule>("none");
  const visible=tasks.filter(t=>filter==="done"?t.completed:filter==="today"?t.dueDate===today()&&!t.completed:filter==="overdue"?!!t.dueDate&&t.dueDate<today()&&!t.completed:true);
  const add=()=>{if(!title.trim())return;addTask({title:title.trim(),priority,dueDate:due||undefined,repeat});setTitle("");setOpen(false)};
  const label=(p:Priority)=>p==="high"?"Высокий":p==="low"?"Низкий":"Средний";
  return <Page title="Задачи" action={<button className="primary rounded-full p-3" onClick={()=>setOpen(true)}><Plus/></button>}>
    <div className="mb-4 flex gap-2 overflow-x-auto">{[["all","Все"],["today","Сегодня"],["overdue","Просрочены"],["done","Готово"]].map(([v,l])=><button key={v} onClick={()=>setFilter(v)} className={`whitespace-nowrap rounded-full px-3 py-2 text-sm ${filter===v?"primary":"bg-black/5 dark:bg-white/10"}`}>{l}</button>)}</div>
    <div className="mb-4 grid grid-cols-3 gap-2"><div className="card p-3"><div className="muted text-xs">Всего</div><b className="text-xl">{tasks.length}</b></div><div className="card p-3"><div className="muted text-xs">Открыто</div><b className="text-xl">{tasks.filter(t=>!t.completed).length}</b></div><div className="card p-3"><div className="muted text-xs">Готово</div><b className="text-xl">{tasks.filter(t=>t.completed).length}</b></div></div>
    <div className="space-y-3">{visible.map(t=><div className={`card flex items-center gap-3 p-4 ${t.completed?"opacity-60":""}`} key={t.id}><button onClick={()=>toggleTask(t.id)} className={`flex h-7 w-7 shrink-0 items-center justify-center rounded-full border-2 ${t.completed?"bg-green-500 text-white":""}`}>{t.completed&&<Check size={16}/>}</button><div className="min-w-0 flex-1"><div className={`font-semibold ${t.completed?"line-through":""}`}>{t.title}</div><div className="mt-1 flex flex-wrap gap-2"><Pill>{label(t.priority)}</Pill>{t.dueDate&&<Pill>📅 {t.dueDate}</Pill>}{t.repeat!=="none"&&<Pill>↻ {t.repeat}</Pill>}</div></div><button className="muted" onClick={()=>removeTask(t.id)}><Trash2 size={17}/></button></div>)}</div>
    {open&&<Modal title="Новая задача" onClose={()=>setOpen(false)}><Field label="Название"><Input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="Что нужно сделать?"/></Field><Field label="Приоритет"><Select value={priority} onChange={e=>setPriority(e.target.value as Priority)}><option value="high">Высокий</option><option value="medium">Средний</option><option value="low">Низкий</option></Select></Field><Field label="Дедлайн"><Input type="date" value={due} onChange={e=>setDue(e.target.value)}/></Field><Field label="Повтор"><Select value={repeat} onChange={e=>setRepeat(e.target.value as RepeatRule)}><option value="none">Без повтора</option><option value="daily">Каждый день</option><option value="weekly">Каждую неделю</option><option value="monthly">Каждый месяц</option></Select></Field><button className="primary w-full rounded-xl p-3 font-bold" onClick={add}>Добавить</button></Modal>}
  </Page>
}

function Finance(){
  const {wallets,categories,transactions,addTransaction,removeTransaction,addWallet,addCategory,budgets,addBudget,removeBudget,goals,addGoal,updateGoal,removeGoal}=useStore();
  const [open,setOpen]=useState<"tx"|"wallet"|"cat"|"budget"|"goal"|null>(null);const [type,setType]=useState<TransactionType>("expense"),[amount,setAmount]=useState(""),[cat,setCat]=useState(categories.find(c=>c.type==="expense")?.id??""),[wallet,setWallet]=useState(wallets[0]?.id??""),[comment,setComment]=useState(""),[date,setDate]=useState(today());
  const [wname,setWname]=useState(""),[cname,setCname]=useState(""),[cType,setCType]=useState<TransactionType>("expense"),[bLimit,setBLimit]=useState(""),[bCat,setBCat]=useState(categories.find(c=>c.type==="expense")?.id??""),[goalName,setGoalName]=useState(""),[goalTarget,setGoalTarget]=useState("");
  const income=transactions.filter(t=>t.type==="income").reduce((a,b)=>a+b.amount,0),expense=transactions.filter(t=>t.type==="expense").reduce((a,b)=>a+b.amount,0),balance=wallets.reduce((a,b)=>a+b.balance,0);
  const addTx=()=>{const n=Number(amount);if(!n||!wallet)return;addTransaction({type,amount:n,categoryId:cat,walletId:wallet,comment,date});setAmount("");setComment("");setOpen(null)};
  const expenseCats=categories.filter(c=>c.type==="expense");
  return <Page title="Финансы" action={<button className="primary rounded-full p-3" onClick={()=>setOpen("tx")}><Plus/></button>}>
    <div className="grid grid-cols-2 gap-3"><div className="card p-4"><div className="muted text-sm">Баланс</div><div className="text-2xl font-black">{money(balance)} ₽</div></div><div className="card p-4"><div className="muted text-sm">Расходы</div><div className="text-2xl font-black">{money(expense)} ₽</div></div></div>
    <div className="mt-3 grid grid-cols-2 gap-3"><div className="card p-4"><div className="muted text-sm">Доходы</div><div className="flex items-center gap-2 text-lg font-bold"><TrendingUp size={18}/> {money(income)} ₽</div></div><div className="card p-4"><div className="muted text-sm">Операций</div><div className="text-lg font-bold">{transactions.length}</div></div></div>
    <div className="mt-5 flex gap-2 overflow-x-auto"><button className="rounded-full bg-black/5 px-3 py-2 text-sm dark:bg-white/10" onClick={()=>setOpen("wallet")}>+ Кошелёк</button><button className="rounded-full bg-black/5 px-3 py-2 text-sm dark:bg-white/10" onClick={()=>setOpen("cat")}>+ Категория</button><button className="rounded-full bg-black/5 px-3 py-2 text-sm dark:bg-white/10" onClick={()=>setOpen("budget")}>+ Бюджет</button><button className="rounded-full bg-black/5 px-3 py-2 text-sm dark:bg-white/10" onClick={()=>setOpen("goal")}>+ Цель</button></div>
    <h3 className="mb-2 mt-6 font-black">Кошельки</h3><div className="space-y-2">{wallets.map(w=><div className="card flex justify-between p-4" key={w.id}><span>{w.name}</span><b>{money(w.balance)} {w.currency}</b></div>)}</div>
    <h3 className="mb-2 mt-6 font-black">Последние операции</h3><div className="space-y-2">{[...transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,10).map(t=><div className="card flex items-center gap-3 p-4" key={t.id}><div className="flex-1"><b>{categories.find(c=>c.id===t.categoryId)?.name??"Категория"}</b><div className="muted text-xs">{t.date}{t.comment?` · ${t.comment}`:""}</div></div><b className={t.type==="income"?"text-green-600":"text-red-500"}>{t.type==="income"?"+":"-"}{money(t.amount)} ₽</b><button className="muted" onClick={()=>removeTransaction(t.id)}><Trash2 size={16}/></button></div>)}</div>
    <h3 className="mb-2 mt-6 font-black">Бюджеты</h3>{budgets.length?budgets.map(b=>{const spent=transactions.filter(t=>t.type==="expense"&&t.categoryId===b.categoryId&&t.date.slice(0,7)===b.month).reduce((a,x)=>a+x.amount,0);const p=Math.min(100,Math.round(spent/b.limit*100));return <div className="card mb-2 p-4" key={b.id}><div className="flex justify-between"><b>{categories.find(c=>c.id===b.categoryId)?.name}</b><span>{money(spent)} / {money(b.limit)} ₽</span></div><div className="mt-2 h-2 rounded bg-black/10"><div className="primary h-2 rounded" style={{width:`${p}%`}}/></div><button className="muted mt-2 text-xs" onClick={()=>removeBudget(b.id)}>Удалить</button></div>}):<div className="muted text-sm">Бюджетов пока нет.</div>}
    <h3 className="mb-2 mt-6 font-black">Цели накопления</h3>{goals.length?goals.map(g=>{const p=Math.min(100,Math.round(g.saved/g.target*100));return <div className="card mb-2 p-4" key={g.id}><div className="flex justify-between"><b>{g.name}</b><span>{p}%</span></div><div className="muted text-sm">{money(g.saved)} / {money(g.target)} ₽</div><div className="mt-2 h-2 rounded bg-black/10"><div className="primary h-2 rounded" style={{width:`${p}%`}}/></div><div className="mt-2 flex gap-3 text-xs"><button className="muted" onClick={()=>updateGoal(g.id,{saved:Math.min(g.target,g.saved+100)})}>+100</button><button className="muted" onClick={()=>removeGoal(g.id)}>Удалить</button></div></div>}):<div className="muted text-sm">Целей пока нет.</div>}
    {open==="tx"&&<Modal title="Новая операция" onClose={()=>setOpen(null)}><div className="mb-3 grid grid-cols-2 gap-2"><button className={`rounded-xl p-3 ${type==="expense"?"primary": "bg-black/5 dark:bg-white/10"}`} onClick={()=>{setType("expense");setCat(expenseCats[0]?.id??"")}}>Расход</button><button className={`rounded-xl p-3 ${type==="income"?"primary": "bg-black/5 dark:bg-white/10"}`} onClick={()=>{setType("income");setCat(categories.find(c=>c.type==="income")?.id??"")}}>Доход</button></div><Field label="Сумма"><Input type="number" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></Field><Field label="Категория"><Select value={cat} onChange={e=>setCat(e.target.value)}>{categories.filter(c=>c.type===type).map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Select></Field><Field label="Кошелёк"><Select value={wallet} onChange={e=>setWallet(e.target.value)}>{wallets.map(w=><option value={w.id} key={w.id}>{w.name}</option>)}</Select></Field><Field label="Дата"><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></Field><Field label="Комментарий"><Input value={comment} onChange={e=>setComment(e.target.value)}/></Field><button className="primary w-full rounded-xl p-3 font-bold" onClick={addTx}>Сохранить</button></Modal>}
    {open==="wallet"&&<Modal title="Новый кошелёк" onClose={()=>setOpen(null)}><Field label="Название"><Input value={wname} onChange={e=>setWname(e.target.value)} placeholder="Наличные"/></Field><button className="primary w-full rounded-xl p-3 font-bold" onClick={()=>{if(wname.trim()){addWallet({name:wname.trim(),balance:0,currency:"₽"});setWname("");setOpen(null)}}}>Создать</button></Modal>}
    {open==="cat"&&<Modal title="Новая категория" onClose={()=>setOpen(null)}><Field label="Название"><Input value={cname} onChange={e=>setCname(e.target.value)}/></Field><Field label="Тип"><Select value={cType} onChange={e=>setCType(e.target.value as TransactionType)}><option value="expense">Расход</option><option value="income">Доход</option></Select></Field><button className="primary w-full rounded-xl p-3 font-bold" onClick={()=>{if(cname.trim()){addCategory({name:cname.trim(),type:cType,color:"#2481cc"});setCname("");setOpen(null)}}}>Создать</button></Modal>}
    {open==="budget"&&<Modal title="Новый бюджет" onClose={()=>setOpen(null)}><Field label="Категория"><Select value={bCat} onChange={e=>setBCat(e.target.value)}>{expenseCats.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</Select></Field><Field label="Лимит на месяц"><Input type="number" value={bLimit} onChange={e=>setBLimit(e.target.value)}/></Field><button className="primary w-full rounded-xl p-3 font-bold" onClick={()=>{if(Number(bLimit)&&bCat){addBudget({categoryId:bCat,month:today().slice(0,7),limit:Number(bLimit)});setBLimit("");setOpen(null)}}}>Создать</button></Modal>}
    {open==="goal"&&<Modal title="Цель накопления" onClose={()=>setOpen(null)}><Field label="Название"><Input value={goalName} onChange={e=>setGoalName(e.target.value)} placeholder="Новый телефон"/></Field><Field label="Цель"><Input type="number" value={goalTarget} onChange={e=>setGoalTarget(e.target.value)} placeholder="0"/></Field><button className="primary w-full rounded-xl p-3 font-bold" onClick={()=>{if(goalName.trim()&&Number(goalTarget)){addGoal({name:goalName.trim(),target:Number(goalTarget),saved:0});setGoalName("");setGoalTarget("");setOpen(null)}}}>Создать</button></Modal>}
  </Page>
}

function Analytics(){
  const {habits,tasks,transactions,categories,goals}=useStore();const inc=transactions.filter(t=>t.type==="income").reduce((a,b)=>a+b.amount,0),exp=transactions.filter(t=>t.type==="expense").reduce((a,b)=>a+b.amount,0);
  const data=categories.filter(c=>c.type==="expense").map(c=>({name:c.name,value:transactions.filter(t=>t.type==="expense"&&t.categoryId===c.id).reduce((a,b)=>a+b.amount,0)})).filter(x=>x.value>0);
  const done=habits.reduce((a,h)=>a+h.completions.length,0), streak=habits.length?Math.max(...habits.map(h=>calcStreak(h.completions))):0, taskPct=tasks.length?Math.round(tasks.filter(t=>t.completed).length/tasks.length*100):0;
  return <Page title="Аналитика"><div className="grid grid-cols-2 gap-3"><div className="card p-4"><div className="muted text-sm">🔥 Лучший streak</div><b className="text-2xl">{streak} дн.</b></div><div className="card p-4"><div className="muted text-sm">✓ Задачи</div><b className="text-2xl">{taskPct}%</b></div><div className="card p-4"><div className="muted text-sm">Доходы</div><b className="text-xl">{money(inc)} ₽</b></div><div className="card p-4"><div className="muted text-sm">Расходы</div><b className="text-xl">{money(exp)} ₽</b></div></div>
    <div className="card mt-4 p-4"><h3 className="font-black">Расходы по категориям</h3>{data.length?<div className="h-64"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={90} label>{data.map((_,i)=><Cell key={i}/>)}</Pie><Tooltip formatter={(v)=>`${money(Number(v))} ₽`}/></PieChart></ResponsiveContainer></div>:<div className="muted py-12 text-center">Добавьте расходы, чтобы увидеть диаграмму.</div>}</div>
    <div className="card mt-4 p-4"><h3 className="font-black">Прогресс</h3><div className="mt-3 space-y-3"><div><div className="flex justify-between text-sm"><span>Выполнено привычек</span><b>{done}</b></div></div><div><div className="flex justify-between text-sm"><span>Задач выполнено</span><b>{tasks.filter(t=>t.completed).length}/{tasks.length}</b></div></div><div><div className="flex justify-between text-sm"><span>Целей накопления</span><b>{goals.filter(g=>g.saved>=g.target).length}/{goals.length}</b></div></div></div></div>
  </Page>
}

function Profile(){
  const {premium,patch,resetData,habits,tasks,transactions,telegramUser,gamification}=useStore();const [confirm,setConfirm]=useState(false);
  const p=levelProgress(gamification.xp);
  const exportData=()=>{const data={exportedAt:new Date().toISOString(),habits,tasks,transactions,gamification};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download=`uphabit-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
  return <Page title="Профиль"><div className="card p-5"><div className="flex items-center gap-4"><div className="flex h-16 w-16 items-center justify-center overflow-hidden rounded-3xl primary">{telegramUser?.photoUrl ? <img src={telegramUser.photoUrl} alt="" className="h-full w-full object-cover" /> : <Sparkles/>}</div><div><div className="text-xl font-black">{telegramUser?.firstName ? `${telegramUser.firstName}${telegramUser.lastName ? ` ${telegramUser.lastName}` : ""}` : "UpHabit"}</div><div className="muted">{telegramUser?.username ? `@${telegramUser.username}` : "Личный центр продуктивности"}</div></div></div></div>
    <div className="card mt-4 p-5"><div className="flex items-center justify-between"><div><div className="muted text-sm">Прогресс</div><div className="text-3xl font-black">Level {p.level}</div></div><div className="text-right"><div className="flex items-center justify-end gap-1 font-black"><Zap size={16}/> {gamification.xp} XP</div><div className="muted flex items-center justify-end gap-1 text-sm"><Coins size={14}/> {gamification.coins} монет</div></div></div><div className="mt-4 h-2 rounded-full bg-black/10"><div className="primary h-2 rounded-full" style={{width:`${p.pct}%`}}/></div><div className="muted mt-2 text-xs">{p.current} / {p.needed} XP до Level {p.level+1}</div></div>
    <div className="mt-4"><div className="mb-3 flex items-center justify-between"><h3 className="font-black">🏆 Достижения</h3><Pill>{gamification.achievements.length}/{ACHIEVEMENTS.length}</Pill></div><div className="grid grid-cols-2 gap-2">{ACHIEVEMENTS.map(a=>{const unlocked=gamification.achievements.includes(a.id);return <div key={a.id} className={`card p-3 ${unlocked?"":"opacity-45"}`}><div className="text-2xl">{a.icon}</div><div className="mt-1 font-bold text-sm">{a.title}</div><div className="muted text-xs">{a.desc}</div></div>})}</div></div>
    <div className="mt-4 space-y-2"><button className="card flex w-full items-center gap-3 p-4 text-left" onClick={()=>patch({premium:!premium})}><Sparkles size={19}/><span className="flex-1"><b>Premium</b><div className="muted text-xs">Демо-переключатель для будущей подписки</div></span><Pill>{premium?"Включён":"Выключен"}</Pill></button><button className="card flex w-full items-center gap-3 p-4 text-left" onClick={exportData}><Download size={19}/><span><b>Экспорт данных</b><div className="muted text-xs">JSON-резервная копия</div></span></button><button className="card flex w-full items-center gap-3 p-4 text-left" onClick={()=>setConfirm(true)}><RotateCcw size={19}/><span><b>Сбросить данные</b><div className="muted text-xs">Удалить локальные данные приложения</div></span></button></div>
    {confirm&&<Modal title="Сбросить UpHabit?" onClose={()=>setConfirm(false)}><p className="muted mb-4">Все привычки, задачи и финансы будут удалены из текущего хранилища.</p><button className="w-full rounded-xl bg-red-500 p-3 font-bold text-white" onClick={()=>{resetData();setConfirm(false)}}>Да, сбросить</button></Modal>}
  </Page>
}

function Onboarding({onDone}:{onDone:()=>void}){return <div className="flex min-h-screen items-center justify-center p-6"><div className="w-full max-w-lg text-center"><div className="mx-auto mb-5 flex h-24 w-24 items-center justify-center rounded-[28px] primary shadow-lg"><Target size={48}/></div><h1 className="text-4xl font-black">UpHabit</h1><p className="muted mt-3 text-lg">Привычки, задачи и финансы — в одном месте.</p><div className="card mt-7 space-y-4 p-5 text-left"><div>🔥 Отслеживайте привычки и streaks</div><div>✓ Управляйте задачами и дедлайнами</div><div>💰 Контролируйте расходы и накопления</div><div>📊 Анализируйте прогресс</div></div><button className="primary mt-5 w-full rounded-2xl p-4 text-lg font-black" onClick={onDone}>Начать</button></div></div>}

export default function App(){
  const {hydrated,onboardingDone,patch}=useStore();const [tab,setTab]=useState<Tab>("habits");const [dark,setDark]=useState(false);
  if(!hydrated)return <div className="flex min-h-screen items-center justify-center font-bold">UpHabit…</div>;
  if(!onboardingDone)return <Onboarding onDone={()=>patch({onboardingDone:true})}/>;
  const nav:[Tab,string,LucideIcon][] =[["habits","Привычки",Target],["tasks","Задачи",CheckSquare],["finance","Финансы",WalletCards],["analytics","Аналитика",BarChart3],["profile","Профиль",Settings]];
  return <div className={dark?"dark":""}><div className="min-h-screen bg-[var(--tg-theme-bg-color,#f4f5f7)] text-[var(--tg-theme-text-color,#111827)]"><div className="mx-auto max-w-2xl px-4 pt-2 text-right"><button className="muted rounded-full p-2" onClick={()=>setDark(v=>!v)}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div>{tab==="habits"?<Habits/>:tab==="tasks"?<Tasks/>:tab==="finance"?<Finance/>:tab==="analytics"?<Analytics/>:<Profile/>}
  <nav className="fixed bottom-0 left-0 right-0 z-40 border-t border-black/5 bg-white/90 px-2 pb-[env(safe-area-inset-bottom)] pt-2 backdrop-blur dark:bg-slate-900/90">{<div className="mx-auto grid max-w-2xl grid-cols-5 gap-1">{nav.map(([k,l,I])=><button key={k} onClick={()=>setTab(k)} className={`flex flex-col items-center rounded-xl py-2 text-[11px] ${tab===k?"primary":"muted bg-transparent"}`}><I size={19}/><span>{l}</span></button>)}</div>}</nav></div></div>
}